export type Option = { label: string; value: string };
export type SubOpt = { label: string; value: string };

export const CATEGORIES: Option[] = [
  { label: "Personlige eiendeler", value: "PERSONAL" },
  { label: "Elektronikk", value: "ELECTRONICS" },
  { label: "Vesker og bagasje", value: "BAGS_LUGGAGE" },
  { label: "Klær og tilbehør", value: "CLOTHING_ACCESSORIES" },
  { label: "Smykker", value: "JEWELRY" },
  { label: "Verktøy", value: "TOOLS_HOUSE" },
  { label: "Bil / transport", value: "VEHICLE_TRANSPORT" },
  { label: "Sport og friluft", value: "SPORT_OUTDOOR" },
  { label: "Kultur og hobby", value: "CULTURE_HOBBY" },
  { label: "Barn og familie", value: "CHILDREN_FAMILY" },
  { label: "Husdyr", value: "PETS" },
];

export const SUBCATEGORIES: Record<string, SubOpt[]> = {
  PERSONAL: [
    { label: "Nøkler", value: "KEYS" }, { label: "Nøkkelknippe", value: "KEYCHAIN" }, { label: "Husnøkkel", value: "HOUSE_KEY" },
    { label: "Lommebok", value: "WALLET" }, { label: "Kontanter", value: "CASH" }, { label: "Mobiltelefon", value: "MOBILE_PHONE" },
    { label: "Solbriller", value: "SUNGLASSES" }, { label: "Vanlige briller", value: "GLASSES" }, { label: "Brilleetui", value: "GLASSES_CASE" },
    { label: "Bankkort", value: "BANK_CARD" }, { label: "Adgangskort", value: "ACCESS_CARD" }, { label: "Adgangsbrikke", value: "ACCESS_TAG" },
    { label: "Reisekort", value: "TRAVEL_CARD" }, { label: "Studentkort", value: "STUDENT_CARD" }, { label: "ID-kort", value: "ID_CARD" },
    { label: "Pass", value: "PASSPORT" }, { label: "Førerkort", value: "DRIVER_LICENSE" }, { label: "Høreapparat", value: "HEARING_AID" },
    { label: "Medisiner", value: "MEDICATION" }, { label: "Medisinbeholder", value: "MEDICATION_CASE" },
    { label: "Kontaktlinseetui", value: "CONTACT_LENS_CASE" }, { label: "Toalettmappe", value: "TOILETRY_BAG" },
    { label: "Parfyme", value: "PERFUME" }, { label: "Navneskilt", value: "NAME_BADGE" }, { label: "Annet (personlige)", value: "OTHER_PERSONAL" },
  ],
  ELECTRONICS: [
    { label: "Hodetelefoner", value: "HEADPHONES" }, { label: "Ørepropper / AirPods", value: "EARBUDS" }, { label: "Ladeetui", value: "CHARGING_CASE" },
    { label: "Smartklokke", value: "SMARTWATCH" }, { label: "Sportsklokke", value: "SPORT_WATCH" }, { label: "Aktivitetsarmbånd", value: "FITNESS_TRACKER" },
    { label: "Nettbrett", value: "TABLET" }, { label: "Bærbar PC", value: "LAPTOP" }, { label: "E-bokleser", value: "E_READER" },
    { label: "Powerbank", value: "POWERBANK" }, { label: "Lader", value: "CHARGER" }, { label: "Ladekabel", value: "CHARGING_CABLE" },
    { label: "Kamera", value: "CAMERA" }, { label: "Actionkamera", value: "ACTION_CAMERA" }, { label: "Kameralinse", value: "CAMERA_LENS" },
    { label: "Minnekort", value: "MEMORY_CARD" }, { label: "USB-minne", value: "USB_DRIVE" }, { label: "Ekstern harddisk", value: "EXTERNAL_DRIVE" },
    { label: "Høyttaler", value: "SPEAKER" }, { label: "Spillkonsoll", value: "GAME_CONSOLE" }, { label: "Spillkontroller", value: "GAME_CONTROLLER" },
    { label: "Elektronisk penn", value: "STYLUS" }, { label: "GPS", value: "GPS_DEVICE" }, { label: "Sporingsbrikke", value: "TRACKER_TAG" },
    { label: "Mobildeksel", value: "PHONE_CASE" }, { label: "Drone", value: "DRONE" }, { label: "Dronekontroller", value: "DRONE_CONTROLLER" },
    { label: "Dronebatteri", value: "DRONE_BATTERY" }, { label: "Annet (elektronikk)", value: "OTHER_ELECTRONICS" },
  ],
  BAGS_LUGGAGE: [
    { label: "Ryggsekk", value: "BACKPACK" }, { label: "Håndveske", value: "HANDBAG" }, { label: "Skulderveske", value: "SHOULDER_BAG" },
    { label: "Belteveske", value: "WAIST_BAG" }, { label: "Koffert", value: "SUITCASE" }, { label: "Kabinkoffert", value: "CABIN_SUITCASE" },
    { label: "Reisebag", value: "TRAVEL_BAG" }, { label: "Treningsbag", value: "GYM_BAG" }, { label: "Sportsbag", value: "SPORTS_BAG" },
    { label: "PC-veske", value: "LAPTOP_BAG" }, { label: "Kameraveske", value: "CAMERA_BAG" }, { label: "Verktøybag", value: "TOOL_BAG" },
    { label: "Dokumentmappe", value: "DOCUMENT_BRIEFCASE" }, { label: "Skolesekk", value: "SCHOOL_BAG" }, { label: "Reisebagasje", value: "TRAVEL_LUGGAGE" },
    { label: "Handlepose", value: "SHOPPING_BAG" }, { label: "Tote-bag", value: "TOTE_BAG" }, { label: "Annet (veske/bagasje)", value: "OTHER_BAGS" },
  ],
  CLOTHING_ACCESSORIES: [
    { label: "Jakke", value: "JACKET" }, { label: "Regnjakke", value: "RAIN_JACKET" }, { label: "Dunjakke", value: "DOWN_JACKET" },
    { label: "Fleecejakke", value: "FLEECE_JACKET" }, { label: "Vest", value: "VEST" }, { label: "Genser", value: "SWEATER" },
    { label: "Hettegenser", value: "HOODIE" }, { label: "Cardigan", value: "CARDIGAN" }, { label: "Fleecegenser", value: "FLEECE" },
    { label: "Skjorte", value: "SHIRT" }, { label: "T-skjorte", value: "T_SHIRT" }, { label: "Topp", value: "TOP" },
    { label: "Bukse", value: "TROUSERS" }, { label: "Shorts", value: "SHORTS" }, { label: "Kjole", value: "DRESS" }, { label: "Skjørt", value: "SKIRT" },
    { label: "Lue", value: "HAT" }, { label: "Caps", value: "CAP" }, { label: "Hatt", value: "BRIMMED_HAT" },
    { label: "Hansker / votter", value: "GLOVES" }, { label: "Skjerf", value: "SCARF" }, { label: "Belte", value: "BELT" }, { label: "Slips", value: "TIE" },
    { label: "Sko", value: "SHOES" }, { label: "Joggesko", value: "SNEAKERS" }, { label: "Støvler", value: "BOOTS" }, { label: "Sandaler", value: "SANDALS" },
    { label: "Paraply", value: "UMBRELLA" }, { label: "Refleksvest", value: "REFLECTIVE_VEST" }, { label: "Annet (klær/tilbehør)", value: "OTHER_CLOTHING" },
  ],
  JEWELRY: [
    { label: "Ring", value: "RING" }, { label: "Giftering", value: "WEDDING_RING" }, { label: "Forlovelsesring", value: "ENGAGEMENT_RING" },
    { label: "Signetring", value: "SIGNET_RING" }, { label: "Øredobber", value: "EARRINGS" }, { label: "Halskjede", value: "NECKLACE" },
    { label: "Anheng", value: "PENDANT" }, { label: "Armbånd", value: "BRACELET" }, { label: "Fotlenke", value: "ANKLET" },
    { label: "Klokke", value: "WATCH" }, { label: "Brosje", value: "BROOCH" }, { label: "Mansjettknapper", value: "CUFFLINKS" },
    { label: "Smykkeskrin", value: "JEWELRY_BOX" }, { label: "Annet (smykker)", value: "OTHER_JEWELRY" },
  ],
  TOOLS_HOUSE: [
    { label: "Verktøy (generelt)", value: "TOOLS" }, { label: "Verktøykasse", value: "TOOLBOX" }, { label: "Drill", value: "DRILL" },
    { label: "Batteriverktøy", value: "POWER_TOOL" }, { label: "Verktøybatteri", value: "TOOL_BATTERY" }, { label: "Måleinstrument", value: "MEASURING_TOOL" },
    { label: "Multimeter", value: "MULTIMETER" }, { label: "Laser", value: "LASER_TOOL" }, { label: "Hørselvern", value: "HEARING_PROTECTION" },
    { label: "Vernebriller", value: "SAFETY_GLASSES" }, { label: "Walkie-talkie", value: "WALKIE_TALKIE" }, { label: "Annet (verktøy)", value: "OTHER_TOOLS" },
  ],
  VEHICLE_TRANSPORT: [
    { label: "Bilnøkler", value: "CAR_KEYS" }, { label: "Sykkel", value: "BICYCLE" }, { label: "Elsykkel", value: "E_BIKE" },
    { label: "Sparkesykkel", value: "SCOOTER" }, { label: "Elsparkesykkel", value: "E_SCOOTER" }, { label: "Sykkellås", value: "BIKE_LOCK" },
    { label: "Sykkellykt", value: "BIKE_LIGHT" }, { label: "Sykkelhjelm", value: "BIKE_HELMET" }, { label: "Motorsykkelhjelm", value: "MOTORCYCLE_HELMET" },
    { label: "Sykkelcomputer", value: "BIKE_COMPUTER" }, { label: "Garasjeåpner", value: "GARAGE_REMOTE" }, { label: "Ladebrikke", value: "CHARGING_TAG" },
    { label: "Bildel / tilbehør", value: "VEHICLE_ACCESSORY" }, { label: "Annet (bil/transport)", value: "OTHER_VEHICLE" },
  ],
  SPORT_OUTDOOR: [
    { label: "Discgolfdisk", value: "DISC_GOLF_DISC" }, { label: "Discgolf-driver", value: "DISC_GOLF_DRIVER" },
    { label: "Discgolf-midrange", value: "DISC_GOLF_MIDRANGE" }, { label: "Discgolf-putter", value: "DISC_GOLF_PUTTER" },
    { label: "Discgolfbag", value: "DISC_GOLF_BAG" }, { label: "Fotball", value: "FOOTBALL" }, { label: "Håndball", value: "HANDBALL" },
    { label: "Basketball", value: "BASKETBALL" }, { label: "Volleyball", value: "VOLLEYBALL" }, { label: "Tennisracket", value: "TENNIS_RACKET" },
    { label: "Padelracket", value: "PADEL_RACKET" }, { label: "Badmintonracket", value: "BADMINTON_RACKET" }, { label: "Golfkølle", value: "GOLF_CLUB" },
    { label: "Golfbag", value: "GOLF_BAG" }, { label: "Golfavstandsmåler", value: "GOLF_RANGEFINDER" }, { label: "Fiskestang", value: "FISHING_ROD" },
    { label: "Fiskesnelle", value: "FISHING_REEL" }, { label: "Hodelykt", value: "HEADLAMP" }, { label: "Lommelykt", value: "FLASHLIGHT" },
    { label: "Kompass", value: "COMPASS" }, { label: "Turstav", value: "TREKKING_POLE" }, { label: "Campingutstyr", value: "CAMPING_GEAR" },
    { label: "Telt", value: "TENT" }, { label: "Sovepose", value: "SLEEPING_BAG" }, { label: "Liggeunderlag", value: "SLEEPING_PAD" },
    { label: "Tursekk", value: "HIKING_BACKPACK" }, { label: "Ski", value: "SKIS" }, { label: "Skistav", value: "SKI_POLE" },
    { label: "Snowboard", value: "SNOWBOARD" }, { label: "Hjelm", value: "HELMET" }, { label: "Goggles", value: "GOGGLES" },
    { label: "Svømmebriller", value: "SWIM_GOGGLES" }, { label: "Drikkeflaske", value: "WATER_BOTTLE" }, { label: "Pulsmåler", value: "HEART_RATE_MONITOR" },
    { label: "Redningsvest", value: "LIFE_JACKET" }, { label: "Kajakkåre", value: "KAYAK_PADDLE" }, { label: "Annet (sport/friluft)", value: "OTHER_SPORT" },
  ],
  CULTURE_HOBBY: [
    { label: "Bok", value: "BOOK" }, { label: "Notatbok", value: "NOTEBOOK" }, { label: "Dagbok", value: "DIARY" }, { label: "Pennal", value: "PENCIL_CASE" },
    { label: "Kalkulator", value: "CALCULATOR" }, { label: "Instrument", value: "MUSICAL_INSTRUMENT" }, { label: "Gitar", value: "GUITAR" },
    { label: "Fiolin", value: "VIOLIN" }, { label: "Kunstutstyr", value: "ART_SUPPLIES" }, { label: "Håndarbeid", value: "CRAFT_ITEM" },
    { label: "Brettspill", value: "BOARD_GAME" }, { label: "Spillkort", value: "PLAYING_CARDS" }, { label: "Fjernstyrt kjøretøy", value: "RC_VEHICLE" },
    { label: "Annet (kultur/hobby)", value: "OTHER_HOBBY" },
  ],
  CHILDREN_FAMILY: [
    { label: "Barnevogn", value: "STROLLER" }, { label: "Kosedyr", value: "STUFFED_TOY" }, { label: "Dukke", value: "DOLL" },
    { label: "Smokk", value: "PACIFIER" }, { label: "Tåteflaske", value: "BABY_BOTTLE" }, { label: "Matboks", value: "LUNCH_BOX" },
    { label: "Drikkeflaske", value: "CHILD_WATER_BOTTLE" }, { label: "Leketøy", value: "TOY" }, { label: "Barnesekk", value: "CHILD_BACKPACK" },
    { label: "Barneteppe", value: "BABY_BLANKET" }, { label: "Bæresele", value: "BABY_CARRIER" }, { label: "Annet (barn/familie)", value: "OTHER_CHILDREN" },
  ],
  PETS: [
    { label: "Hund", value: "DOG" }, { label: "Katt", value: "CAT" }, { label: "Fugl", value: "BIRD" }, { label: "Kanin", value: "RABBIT" },
    { label: "Marsvin", value: "GUINEA_PIG" }, { label: "Hamster", value: "HAMSTER" }, { label: "Skilpadde", value: "TURTLE" },
    { label: "Reptil", value: "REPTILE" }, { label: "Hest", value: "HORSE" }, { label: "Halsbånd", value: "PET_COLLAR" },
    { label: "Kobbel", value: "PET_LEASH" }, { label: "Sele", value: "PET_HARNESS" }, { label: "Annet (husdyr)", value: "OTHER_PET" },
    { label: "Egendefinert (skriv selv)", value: "CUSTOM" },
  ],
};

export const OBJECT_LABELS_EN: Record<string, string> = {
  KEYS: "Keys",
  KEYCHAIN: "Keychain",
  HOUSE_KEY: "House key",
  WALLET: "Wallet",
  CASH: "Cash",
  MOBILE_PHONE: "Mobile phone",
  SUNGLASSES: "Sunglasses",
  GLASSES: "Glasses",
  GLASSES_CASE: "Glasses case",
  BANK_CARD: "Bank card",
  ACCESS_CARD: "Access card",
  ACCESS_TAG: "Access tag",
  TRAVEL_CARD: "Travel card",
  STUDENT_CARD: "Student card",
  ID_CARD: "ID card",
  PASSPORT: "Passport",
  DRIVER_LICENSE: "Driver's license",
  HEARING_AID: "Hearing aid",
  MEDICATION: "Medication",
  MEDICATION_CASE: "Medication case",
  CONTACT_LENS_CASE: "Contact lens case",
  TOILETRY_BAG: "Toiletry bag",
  PERFUME: "Perfume",
  NAME_BADGE: "Name badge",
  OTHER_PERSONAL: "Other personal item",
  HEADPHONES: "Headphones",
  EARBUDS: "Earbuds / AirPods",
  CHARGING_CASE: "Charging case",
  SMARTWATCH: "Smartwatch",
  SPORT_WATCH: "Sports watch",
  FITNESS_TRACKER: "Fitness tracker",
  TABLET: "Tablet",
  LAPTOP: "Laptop",
  E_READER: "E-reader",
  POWERBANK: "Power bank",
  CHARGER: "Charger",
  CHARGING_CABLE: "Charging cable",
  CAMERA: "Camera",
  ACTION_CAMERA: "Action camera",
  CAMERA_LENS: "Camera lens",
  MEMORY_CARD: "Memory card",
  USB_DRIVE: "USB drive",
  EXTERNAL_DRIVE: "External drive",
  SPEAKER: "Speaker",
  GAME_CONSOLE: "Game console",
  GAME_CONTROLLER: "Game controller",
  STYLUS: "Stylus",
  GPS_DEVICE: "GPS",
  TRACKER_TAG: "Tracker tag",
  PHONE_CASE: "Phone case",
  DRONE: "Drone",
  DRONE_CONTROLLER: "Drone controller",
  DRONE_BATTERY: "Drone battery",
  OTHER_ELECTRONICS: "Other electronics",
  BACKPACK: "Backpack",
  HANDBAG: "Handbag",
  SHOULDER_BAG: "Shoulder bag",
  WAIST_BAG: "Waist bag",
  SUITCASE: "Suitcase",
  CABIN_SUITCASE: "Cabin suitcase",
  TRAVEL_BAG: "Travel bag",
  GYM_BAG: "Gym bag",
  SPORTS_BAG: "Sports bag",
  LAPTOP_BAG: "Laptop bag",
  CAMERA_BAG: "Camera bag",
  TOOL_BAG: "Tool bag",
  DOCUMENT_BRIEFCASE: "Document case",
  SCHOOL_BAG: "School bag",
  TRAVEL_LUGGAGE: "Travel luggage",
  SHOPPING_BAG: "Shopping bag",
  TOTE_BAG: "Tote bag",
  OTHER_BAGS: "Other bag/luggage",
  JACKET: "Jacket",
  RAIN_JACKET: "Rain jacket",
  DOWN_JACKET: "Down jacket",
  FLEECE_JACKET: "Fleece jacket",
  VEST: "Vest",
  SWEATER: "Sweater",
  HOODIE: "Hoodie",
  CARDIGAN: "Cardigan",
  FLEECE: "Fleece sweater",
  SHIRT: "Shirt",
  T_SHIRT: "T-shirt",
  TOP: "Top",
  TROUSERS: "Trousers",
  SHORTS: "Shorts",
  DRESS: "Dress",
  SKIRT: "Skirt",
  HAT: "Beanie",
  CAP: "Cap",
  BRIMMED_HAT: "Hat",
  GLOVES: "Gloves / mittens",
  SCARF: "Scarf",
  BELT: "Belt",
  TIE: "Tie",
  SHOES: "Shoes",
  SNEAKERS: "Sneakers",
  BOOTS: "Boots",
  SANDALS: "Sandals",
  UMBRELLA: "Umbrella",
  REFLECTIVE_VEST: "Reflective vest",
  OTHER_CLOTHING: "Other clothing/accessory",
  RING: "Ring",
  WEDDING_RING: "Wedding ring",
  ENGAGEMENT_RING: "Engagement ring",
  SIGNET_RING: "Signet ring",
  EARRINGS: "Earrings",
  NECKLACE: "Necklace",
  PENDANT: "Pendant",
  BRACELET: "Bracelet",
  ANKLET: "Anklet",
  WATCH: "Watch",
  BROOCH: "Brooch",
  CUFFLINKS: "Cufflinks",
  JEWELRY_BOX: "Jewelry box",
  OTHER_JEWELRY: "Other jewelry",
  TOOLS: "Tools",
  TOOLBOX: "Toolbox",
  DRILL: "Drill",
  POWER_TOOL: "Power tool",
  TOOL_BATTERY: "Tool battery",
  MEASURING_TOOL: "Measuring tool",
  MULTIMETER: "Multimeter",
  LASER_TOOL: "Laser tool",
  HEARING_PROTECTION: "Hearing protection",
  SAFETY_GLASSES: "Safety glasses",
  WALKIE_TALKIE: "Walkie-talkie",
  OTHER_TOOLS: "Other tools",
  CAR_KEYS: "Car keys",
  BICYCLE: "Bicycle",
  E_BIKE: "E-bike",
  SCOOTER: "Scooter",
  E_SCOOTER: "E-scooter",
  BIKE_LOCK: "Bike lock",
  BIKE_LIGHT: "Bike light",
  BIKE_HELMET: "Bike helmet",
  MOTORCYCLE_HELMET: "Motorcycle helmet",
  BIKE_COMPUTER: "Bike computer",
  GARAGE_REMOTE: "Garage remote",
  CHARGING_TAG: "Charging tag",
  VEHICLE_ACCESSORY: "Vehicle accessory",
  OTHER_VEHICLE: "Other vehicle/transport",
  DISC_GOLF_DISC: "Disc golf disc",
  DISC_GOLF_DRIVER: "Disc golf driver",
  DISC_GOLF_MIDRANGE: "Disc golf midrange",
  DISC_GOLF_PUTTER: "Disc golf putter",
  DISC_GOLF_BAG: "Disc golf bag",
  FOOTBALL: "Football",
  HANDBALL: "Handball",
  BASKETBALL: "Basketball",
  VOLLEYBALL: "Volleyball",
  TENNIS_RACKET: "Tennis racket",
  PADEL_RACKET: "Padel racket",
  BADMINTON_RACKET: "Badminton racket",
  GOLF_CLUB: "Golf club",
  GOLF_BAG: "Golf bag",
  GOLF_RANGEFINDER: "Golf rangefinder",
  FISHING_ROD: "Fishing rod",
  FISHING_REEL: "Fishing reel",
  HEADLAMP: "Headlamp",
  FLASHLIGHT: "Flashlight",
  COMPASS: "Compass",
  TREKKING_POLE: "Trekking pole",
  CAMPING_GEAR: "Camping gear",
  TENT: "Tent",
  SLEEPING_BAG: "Sleeping bag",
  SLEEPING_PAD: "Sleeping pad",
  HIKING_BACKPACK: "Hiking backpack",
  SKIS: "Skis",
  SKI_POLE: "Ski pole",
  SNOWBOARD: "Snowboard",
  HELMET: "Helmet",
  GOGGLES: "Goggles",
  SWIM_GOGGLES: "Swimming goggles",
  WATER_BOTTLE: "Water bottle",
  HEART_RATE_MONITOR: "Heart rate monitor",
  LIFE_JACKET: "Life jacket",
  KAYAK_PADDLE: "Kayak paddle",
  OTHER_SPORT: "Other sport/outdoor item",
  BOOK: "Book",
  NOTEBOOK: "Notebook",
  DIARY: "Diary",
  PENCIL_CASE: "Pencil case",
  CALCULATOR: "Calculator",
  MUSICAL_INSTRUMENT: "Musical instrument",
  GUITAR: "Guitar",
  VIOLIN: "Violin",
  ART_SUPPLIES: "Art supplies",
  CRAFT_ITEM: "Craft item",
  BOARD_GAME: "Board game",
  PLAYING_CARDS: "Playing cards",
  RC_VEHICLE: "Remote-controlled vehicle",
  OTHER_HOBBY: "Other culture/hobby item",
  STROLLER: "Stroller",
  STUFFED_TOY: "Stuffed toy",
  DOLL: "Doll",
  PACIFIER: "Pacifier",
  BABY_BOTTLE: "Baby bottle",
  LUNCH_BOX: "Lunch box",
  CHILD_WATER_BOTTLE: "Child's water bottle",
  TOY: "Toy",
  CHILD_BACKPACK: "Child's backpack",
  BABY_BLANKET: "Baby blanket",
  BABY_CARRIER: "Baby carrier",
  OTHER_CHILDREN: "Other child/family item",
  DOG: "Dog",
  CAT: "Cat",
  BIRD: "Bird",
  RABBIT: "Rabbit",
  GUINEA_PIG: "Guinea pig",
  HAMSTER: "Hamster",
  TURTLE: "Turtle",
  REPTILE: "Reptile",
  HORSE: "Horse",
  PET_COLLAR: "Pet collar",
  PET_LEASH: "Pet leash",
  PET_HARNESS: "Pet harness",
  OTHER_PET: "Other pet",
  CUSTOM: "Custom",
 };

export const OBJECT_ALIASES: Record<string, string[]> = {
  RING: ["ring", "giftering", "forlovelsesring", "wedding ring", "engagement ring"],
  SMARTWATCH: ["smartklokke", "apple watch", "galaxy watch", "smartwatch"], WATCH: ["klokke", "ur", "watch"],
  EARBUDS: ["airpods", "ørepropper", "orepropper", "earbuds", "earphones"], HEADPHONES: ["hodetelefoner", "headphones"],
  DRONE: ["drone", "quadrocopter", "quadcopter"], DRONE_CONTROLLER: ["dronekontroller", "fjernkontroll drone", "drone remote"],
  DISC_GOLF_DISC: ["discgolfdisk", "disc golf disc", "sendeplate", "frisbee"], DISC_GOLF_DRIVER: ["driver", "distance driver", "fairway driver", "sendeplate"],
  DISC_GOLF_MIDRANGE: ["midrange", "mid range", "sendeplate"], DISC_GOLF_PUTTER: ["putter", "putting disc", "sendeplate"],
  HOODIE: ["hettegenser", "hoodie", "hooded sweater"], SWEATER: ["genser", "sweater", "jumper"], CARDIGAN: ["cardigan", "strikkejakke"],
  TRACKER_TAG: ["airtag", "sporingsbrikke", "tracker tag", "smarttag"], KEYS: ["nøkler", "nokler", "keys", "key"],
  KEYCHAIN: ["nøkkelknippe", "nokkelknippe", "keychain", "key ring"], MOBILE_PHONE: ["mobil", "telefon", "iphone", "phone", "cellphone"],
  STUFFED_TOY: ["kosedyr", "bamse", "teddy bear", "stuffed toy"], PACIFIER: ["smokk", "pacifier", "dummy"],
};

export function objectLabel(value?: string, language: "no"|"en" = "no", category?: string) {
  if (!value) return "";
  if (language === "en") return OBJECT_LABELS_EN[value] ?? value;
  if (category) return SUBCATEGORIES[category]?.find(x => x.value === value)?.label ?? value;
  for (const list of Object.values(SUBCATEGORIES)) { const hit=list.find(x=>x.value===value); if(hit) return hit.label; }
  return value;
}
export function objectSearchText(value: string, noLabel: string, enLabel?: string) {
  return [value, noLabel, enLabel ?? OBJECT_LABELS_EN[value] ?? "", ...(OBJECT_ALIASES[value] ?? [])].join(" ");
}
