import * as ImagePicker from "expo-image-picker";
import * as ImageManipulator from "expo-image-manipulator";
import * as DocumentPicker from "expo-document-picker";
import { File } from "expo-file-system";
import { fetch as expoFetch } from "expo/fetch";
import { supabase } from "./supabase";
import { API_BASE_URL } from "./config";
async function jsonFetch<T>(url:string, init?:RequestInit, timeout=20000){const c=new AbortController();const id=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{...(init||{}),signal:c.signal});const text=await r.text();let data:any=null;try{data=text?JSON.parse(text):null}catch{}return{ok:r.ok,status:r.status,data:data as T|null,text}}finally{clearTimeout(id)}}
function svg(uri:string){const u=(uri||"").toLowerCase();return u.includes(".svg")||u.startsWith("data:image/svg")}
async function normalize(uri:string){if(!uri)throw new Error("IMAGE_URI_MISSING");if(svg(uri))throw new Error("IMAGE_TYPE_UNSUPPORTED");const o=await ImageManipulator.manipulateAsync(uri,[{resize:{width:1600}}],{compress:.82,format:ImageManipulator.SaveFormat.JPEG});return o.uri}
export async function pickOneImage(){try{const p=await ImagePicker.requestMediaLibraryPermissionsAsync();if(p.granted){const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:ImagePicker.MediaTypeOptions.Images,allowsEditing:false,quality:1,selectionLimit:1});if(!r.canceled&&r.assets?.[0]?.uri)return normalize(r.assets[0].uri)}}catch{}const d=await DocumentPicker.getDocumentAsync({type:["image/*"],multiple:false,copyToCacheDirectory:true});if(d.canceled)return null;const a=(d as any).assets?.[0]??d as any;return a?.uri?normalize(a.uri):null}
export async function captureOneImage(){const p=await ImagePicker.requestCameraPermissionsAsync();if(!p.granted)return null;const r=await ImagePicker.launchCameraAsync({allowsEditing:false,quality:1});if(r.canceled||!r.assets?.[0]?.uri)return null;return normalize(r.assets[0].uri)}
export type UploadedImage={path:string;url?:string};
const wait=(n:number)=>new Promise(r=>setTimeout(r,n));
async function put(url:string,uri:string){const f=new File(uri);if(!f.exists||!f.size)throw new Error("IMAGE_FILE_UNAVAILABLE");let status=0;for(let i=0;i<2;i++){const r=await expoFetch(url,{method:"PUT",headers:{"Content-Type":"image/jpeg"},body:f as any});if(r.ok)return;status=r.status;if(i===0&&(status===408||status===429||status>=500)){await wait(700);continue}break}throw new Error(`STORAGE_UPLOAD_FAILED_${status||"NETWORK"}`)}
export async function uploadReportImage(reportId:string,localUri:string,sortOrder=0):Promise<UploadedImage>{if(!reportId)throw new Error("REPORT_ID_INVALID");const uri=/\.jpe?g$/i.test(localUri)&&localUri.includes("ImageManipulator")?localUri:await normalize(localUri);const {data:s}=await supabase.auth.getSession();const token=s.session?.access_token;if(!token)throw new Error("AUTH_REQUIRED");const signed=await jsonFetch<any>(`${API_BASE_URL}/storage/signed-upload`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({reportId,ext:"jpg"})});if(!signed.ok||!signed.data?.path||!signed.data?.signedUrl)throw new Error("SIGNED_UPLOAD_FAILED");await put(signed.data.signedUrl,uri);const reg=await jsonFetch<any>(`${API_BASE_URL}/reports/${encodeURIComponent(reportId)}/images`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({path:signed.data.path,sort_order:sortOrder})});if(!reg.ok)throw new Error("IMAGE_REGISTRATION_FAILED");return{path:signed.data.path}}
