import { CATEGORIES, SUBCATEGORIES, objectLabel } from "./categories";
export type AppLanguage = "no" | "en";
const CATEGORY_EN: Record<string,string>={PERSONAL:"Personal belongings",ELECTRONICS:"Electronics",BAGS_LUGGAGE:"Bags and luggage",CLOTHING_ACCESSORIES:"Clothing and accessories",JEWELRY:"Jewelry",TOOLS_HOUSE:"Tools",VEHICLE_TRANSPORT:"Vehicle / transport",SPORT_OUTDOOR:"Sports and outdoors",CULTURE_HOBBY:"Culture and hobbies",CHILDREN_FAMILY:"Children and family",PETS:"Pets"};
const COLOR_NO:Record<string,string>={black:"Svart",white:"Hvit",gray:"Grå",red:"Rød",orange:"Oransje",yellow:"Gul",green:"Grønn",blue:"Blå",purple:"Lilla",brown:"Brun",pink:"Rosa",beige:"Beige",navy:"Mørkeblå",silver:"Sølv",gold:"Gull",multicolor:"Flerfarget"};
const COLOR_EN:Record<string,string>={black:"Black",white:"White",gray:"Gray",red:"Red",orange:"Orange",yellow:"Yellow",green:"Green",blue:"Blue",purple:"Purple",brown:"Brown",pink:"Pink",beige:"Beige",navy:"Navy",silver:"Silver",gold:"Gold",multicolor:"Multicolor"};
const normalize=(v:any)=>String(v||"").trim().toUpperCase().replace(/[ -]+/g,"_");
export function categoryLabel(value:any,language:AppLanguage){const key=normalize(value);if(language==="en")return CATEGORY_EN[key]||String(value||"");return CATEGORIES.find(x=>x.value===key)?.label||String(value||"");}
export function itemLabel(value:any,language:AppLanguage,category?:any){return objectLabel(normalize(value),language,normalize(category))||String(value||"");}
export function colorLabel(value:any,language:AppLanguage){const key=String(value||"").trim().toLowerCase();return (language==="en"?COLOR_EN:COLOR_NO)[key]||String(value||"");}
export function reportSummary(report:any,language:AppLanguage){if(!report)return "";const type=String(report.type||"").toUpperCase()==="FOUND"?(language==="en"?"Found":"Funnet"):(language==="en"?"Lost":"Mistet");return [type,categoryLabel(report.category,language),itemLabel(report.subcategory_key,language,report.category),colorLabel(report.color,language)].filter(Boolean).join(" • ");}
export function localizeStoredReportTitle(title:any,language:AppLanguage){const raw=String(title||"").trim();if(!raw)return "";const parts=raw.split("•").map(x=>x.trim()).filter(Boolean);return parts.map((part,index)=>{if(index===0&&/^(mistet|lost)$/i.test(part))return language==="en"?"Lost":"Mistet";if(index===0&&/^(funnet|found)$/i.test(part))return language==="en"?"Found":"Funnet";for(const c of CATEGORIES)if(c.label.toLowerCase()===part.toLowerCase())return categoryLabel(c.value,language);for(const [cat,list] of Object.entries(SUBCATEGORIES))for(const x of list)if(x.label.toLowerCase()===part.toLowerCase())return itemLabel(x.value,language,cat);for(const [key,label] of Object.entries(COLOR_NO))if(label.toLowerCase()===part.toLowerCase())return colorLabel(key,language);return part}).join(" • ");}
export function notificationCaseLabel(report:any,language:AppLanguage){if(!report)return "";const type=String(report.type||"").toUpperCase()==="FOUND"?(language==="en"?"Found":"Funnet"):(language==="en"?"Lost":"Mistet");const item=String(report.subcategory_custom||itemLabel(report.subcategory_key,language,report.category)||"").trim().toLowerCase();const color=colorLabel(report.color,language).trim().toLowerCase();return [type,color,item].filter(Boolean).join(" ").replace(/\s+/g," ").trim();}
