"use strict";
const express=require("express");const router=express.Router();const {supaAdmin}=require("../supabaseClient");const {requireUser}=require("../mw/auth");const {notifyUser}=require("../lib/userNotify");
async function parties(kind,id){
 if(kind==="OBSERVATION"){const q=await supaAdmin.from("area_alert_observations").select("id,report_id,observer_user_id,report_owner_user_id,campaign_id").eq("id",id).maybeSingle();if(q.error)throw q.error;return q.data?{a:q.data.observer_user_id,b:q.data.report_owner_user_id,reportIds:[q.data.report_id],observation:q.data}:null;}
 const q=await supaAdmin.from("matches").select("id,lost_id,found_id,lost:lost_id(user_id),found:found_id(user_id)").eq("id",id).maybeSingle();if(q.error)throw q.error;return q.data?{a:q.data.lost?.user_id,b:q.data.found?.user_id,reportIds:[q.data.lost_id,q.data.found_id]}:null;
}
router.post("/propose",requireUser,async(req,res)=>{try{const kind=String(req.body?.contextType||"").toUpperCase(),id=String(req.body?.contextId||"");if(!["MATCH","OBSERVATION"].includes(kind))return res.status(400).json({error:"INVALID_CONTEXT"});const p=await parties(kind,id);if(!p||![p.a,p.b].includes(req.user.id))return res.status(404).json({error:"CONTEXT_NOT_FOUND"});const other=req.user.id===p.a?p.b:p.a;const x=await supaAdmin.from("resolution_proposals").insert({context_type:kind,context_id:id,proposed_by:req.user.id,requested_from:other}).select("*").single();if(x.error){if(x.error.code==="23505")return res.status(409).json({error:"RESOLUTION_ALREADY_PENDING"});throw x.error;}await notifyUser({userId:other,type:"RESOLUTION_PROPOSED",entityType:kind==="MATCH"?"match":"observation",entityId:id,title:"Forslag om å avslutte saken",body:"Motparten foreslår at saken markeres som løst."});return res.json({ok:true,proposal:x.data});}catch(e){return res.status(500).json({error:e?.message||"RESOLUTION_PROPOSE_FAILED"});}});
router.post("/:id/respond",requireUser,async(req,res)=>{try{const accept=req.body?.accept===true;const q=await supaAdmin.from("resolution_proposals").select("*").eq("id",req.params.id).eq("requested_from",req.user.id).eq("status","PENDING").maybeSingle();if(q.error)throw q.error;if(!q.data)return res.status(404).json({error:"PROPOSAL_NOT_FOUND"});const p=await parties(q.data.context_type,q.data.context_id);if(!p)return res.status(404).json({error:"CONTEXT_NOT_FOUND"});if(!accept){await supaAdmin.from("resolution_proposals").update({status:"REJECTED",responded_at:new Date().toISOString()}).eq("id",q.data.id);await notifyUser({userId:q.data.proposed_by,type:"RESOLUTION_REJECTED",entityType:q.data.context_type==="MATCH"?"match":"observation",entityId:q.data.context_id,title:"Forslaget ble ikke bekreftet",body:"Motparten bekreftet ikke at saken er løst."});return res.json({ok:true,accepted:false});}
 const now=new Date().toISOString();for(const rid of p.reportIds.filter(Boolean)){await supaAdmin.from("reports").update({status:"CLOSED",closed_at:now}).eq("id",rid);await supaAdmin.from("geo_alert_campaigns").update({status:"COMPLETED",completed_at:now,updated_at:now}).eq("report_id",rid).eq("status","ACTIVE");await supaAdmin.from("report_entitlements").update({status:"CANCELLED",cancelled_at:now,updated_at:now}).eq("report_id",rid).eq("status","ACTIVE").like("product_code","GEO_ALERT_TIER_%");}
 if(q.data.context_type==="OBSERVATION")await supaAdmin.from("area_alert_observations").update({status:"CONFIRMED",updated_at:now}).eq("id",q.data.context_id);
 await supaAdmin.from("resolution_proposals").update({status:"ACCEPTED",responded_at:now}).eq("id",q.data.id);await notifyUser({userId:q.data.proposed_by,type:"RESOLUTION_CONFIRMED",entityType:q.data.context_type==="MATCH"?"match":"observation",entityId:q.data.context_id,title:"Saken er bekreftet løst",body:"Motparten har bekreftet at saken er løst."});return res.json({ok:true,accepted:true});
}catch(e){return res.status(500).json({error:e?.message||"RESOLUTION_RESPONSE_FAILED"});}});
router.get("/pending",requireUser,async(req,res)=>{const q=await supaAdmin.from("resolution_proposals").select("*").eq("requested_from",req.user.id).eq("status","PENDING").order("created_at",{ascending:false});if(q.error)return res.status(400).json({error:q.error.message});return res.json({proposals:q.data||[]});});module.exports=router;
