import React, { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, View } from "react-native";
import { Stack, useLocalSearchParams, useRouter } from "expo-router";
import { PremiumHeader } from "../../src/ui/PremiumHeader";
import { theme } from "../../src/ui/theme";
import { useI18n } from "../../src/i18n/I18nProvider";
import { API_BASE_URL } from "../../src/lib/config";
import { supabase } from "../../src/lib/supabase";
export default function ObservationDetails(){
 const router=useRouter(); const {language}=useI18n(); const {id}=useLocalSearchParams<{id:string}>(); const [loading,setLoading]=useState(true); const [observation,setObservation]=useState<any>(null);
 const load=useCallback(async()=>{try{setLoading(true);const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error(language==="en"?"You must be logged in.":"Du må være innlogget.");const r=await fetch(`${API_BASE_URL}/observations/${encodeURIComponent(String(id||""))}`,{headers:{Authorization:`Bearer ${token}`}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error||`HTTP_${r.status}`);setObservation(j.observation);}catch(e:any){Alert.alert(language==="en"?"Could not open observation":"Kunne ikke åpne observasjonen",e?.message||String(e));}finally{setLoading(false);}},[id,language]);
 useEffect(()=>{void load();},[load]); const report=observation?.reports; const found=observation?.observation_type==="FOUND";
 return <><Stack.Screen options={{headerShown:false}}/><View style={styles.safe}><PremiumHeader title={found?(language==="en"?"Possible find":"Mulig funn"):(language==="en"?"Observation":"Observasjon")} onBack={()=>router.back()}/>{loading?<View style={styles.center}><ActivityIndicator/></View>:!observation?<View style={styles.center}><Text>{language==="en"?"Observation unavailable.":"Observasjonen er ikke tilgjengelig."}</Text></View>:<ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><Text style={styles.eyebrow}>{found?(language==="en"?"POSSIBLE FIND":"MULIG FUNN"):(language==="en"?"SIGHTING":"OBSERVASJON")}</Text><Text style={styles.title}>{report?.title||"–"}</Text></View><View style={styles.card}><Text style={styles.h2}>{language==="en"?"Information":"Opplysninger"}</Text><Text style={styles.row}>{language==="en"?"Observed":"Tidspunkt"}: {new Date(observation.observed_at).toLocaleString(language==="en"?"en-GB":"nb-NO")}</Text><Text style={styles.row}>{language==="en"?"Comment":"Kommentar"}: {observation.comment||"–"}</Text>{!found&&<Text style={styles.row}>{language==="en"?"Direction":"Retning"}: {observation.movement_direction||"–"}</Text>}{found&&<Text style={styles.row}>{observation.has_item?(language==="en"?"The item or animal is with the observer.":"Gjenstanden eller dyret er hos observatøren."):(language==="en"?"The location was reported, but the item is not confirmed secured.":"Stedet er meldt, men gjenstanden er ikke bekreftet sikret.")}</Text>}<Text style={styles.row}>{language==="en"?"Position":"Posisjon"}: {Number(observation.latitude).toFixed(5)}, {Number(observation.longitude).toFixed(5)}</Text><Text style={styles.row}>{language==="en"?"Status":"Status"}: {observation.status==="NEW"?(language==="en"?"New":"Ny"):observation.status}</Text></View><View style={styles.info}><Text style={styles.infoText}>{language==="en"?"This does not close the lost report automatically. The owner must assess and confirm the information.":"Dette avslutter ikke LOST-rapporten automatisk. Eieren må vurdere og bekrefte opplysningen."}</Text></View></ScrollView>}</View></>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:theme.colors.bg},center:{flex:1,alignItems:"center",justifyContent:"center"},content:{padding:14,paddingBottom:40},hero:{padding:18,borderRadius:18,backgroundColor:"#EFF6FF",borderWidth:1,borderColor:"#93C5FD"},eyebrow:{fontSize:11,fontWeight:"900",color:"#1D4ED8"},title:{marginTop:7,fontSize:23,fontWeight:"900",color:theme.colors.text},card:{marginTop:12,padding:16,borderRadius:18,backgroundColor:theme.colors.card,borderWidth:1,borderColor:theme.colors.border},h2:{fontSize:17,fontWeight:"900",color:theme.colors.text},row:{marginTop:10,fontWeight:"700",lineHeight:20,color:theme.colors.text},info:{marginTop:12,padding:14,borderRadius:14,backgroundColor:"#F8FAFC",borderWidth:1,borderColor:theme.colors.border},infoText:{fontWeight:"700",lineHeight:19,color:theme.colors.muted}});
