import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ActivityIndicator, Alert, FlatList, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import MapView, { Circle, Marker, Polygon, PROVIDER_GOOGLE, Region } from "react-native-maps";
import * as Location from "expo-location";
import { Stack, useRouter } from "expo-router";
import { PremiumHeader } from "../src/ui/PremiumHeader";
import { theme } from "../src/ui/theme";
import { useI18n } from "../src/i18n/I18nProvider";
import { supabase } from "../src/lib/supabase";
import { API_BASE_URL } from "../src/lib/config";

type Point = { latitude: number; longitude: number };
type AreaMode = "CIRCLE" | "POLYGON";
type Area = { id:string; name:string; area_type?:AreaMode; latitude:number|null; longitude:number|null; radius_m:number|null; boundary_points?:Point[]; category_keys:string[]; all_categories:boolean; push_enabled:boolean; active:boolean };
const RADII=[250,500,1000,3000,5000,10000];
const CATEGORIES=["PETS","JEWELRY","ELECTRONICS","KEYS","BAGS","CLOTHING","SPORTS","TRANSPORT"];
const LABELS:Record<string,{no:string;en:string}>={PETS:{no:"Husdyr",en:"Pets"},JEWELRY:{no:"Smykker",en:"Jewelry"},ELECTRONICS:{no:"Elektronikk",en:"Electronics"},KEYS:{no:"Nøkler",en:"Keys"},BAGS:{no:"Vesker",en:"Bags"},CLOTHING:{no:"Klær",en:"Clothing"},SPORTS:{no:"Sport",en:"Sports"},TRANSPORT:{no:"Transport",en:"Transport"}};
const isPoint=(p:any):p is Point=>Number.isFinite(Number(p?.latitude))&&Number.isFinite(Number(p?.longitude));
export default function AlertAreasScreen(){
 const router=useRouter();const {language,t}=useI18n();const mapRef=useRef<MapView>(null);
 const [areas,setAreas]=useState<Area[]>([]),[name,setName]=useState(""),[center,setCenter]=useState<Point>({latitude:59.9139,longitude:10.7522}),[radius,setRadius]=useState(1000),[mode,setMode]=useState<AreaMode>("CIRCLE"),[points,setPoints]=useState<Point[]>([]),[allCategories,setAllCategories]=useState(true),[categories,setCategories]=useState<string[]>([]),[busy,setBusy]=useState(false),[query,setQuery]=useState(""),[searching,setSearching]=useState(false),[results,setResults]=useState<any[]>([]);
 const region=useMemo<Region>(()=>({...center,latitudeDelta:.08,longitudeDelta:.08}),[]);
 const headers=useCallback(async()=>{const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error("LOGIN_REQUIRED");return {"Content-Type":"application/json",Authorization:`Bearer ${token}`};},[]);
 const friendly=(e:any,fallback:string)=>String(e?.message||e)==="LOGIN_REQUIRED"?t("alertAreas.loginRequired"):fallback;
 const load=useCallback(async()=>{try{const r=await fetch(`${API_BASE_URL}/alert-areas`,{headers:await headers()});const j=await r.json();if(!r.ok)throw new Error(j.error);setAreas(j.areas||[]);}catch(e:any){Alert.alert(t("alertAreas.error"),friendly(e,t("alertAreas.loadFailed")));}},[headers,t]);
 useEffect(()=>{void load()},[load]);
 const locate=async()=>{const p=await Location.requestForegroundPermissionsAsync();if(p.status!=="granted")return;const pos=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});const next={latitude:pos.coords.latitude,longitude:pos.coords.longitude};setCenter(next);setPoints([]);mapRef.current?.animateToRegion({...next,latitudeDelta:.03,longitudeDelta:.03},250)};
 const search=async()=>{const q=query.trim();if(q.length<3)return;try{setSearching(true);const r=await fetch(`${API_BASE_URL}/geo/search?q=${encodeURIComponent(q)}&language=${encodeURIComponent(language)}`,{headers:await headers()});const j=await r.json();if(!r.ok)throw new Error(j.error);setResults(j.results||[]);}catch(e:any){Alert.alert(t("alertAreas.error"),friendly(e,t("alertAreas.searchFailed")));}finally{setSearching(false)}};
 const chooseResult=(item:any)=>{const next={latitude:Number(item.latitude),longitude:Number(item.longitude)};if(!isPoint(next))return;setCenter(next);setPoints([]);setQuery(String(item.label||""));setResults([]);mapRef.current?.animateToRegion({...next,latitudeDelta:.02,longitudeDelta:.02},250)};
 const mapPress=(coordinate:Point)=>{if(mode==="CIRCLE"){setCenter(coordinate);return}setPoints(v=>[...v,coordinate]);};
 const toggle=(key:string)=>{setAllCategories(false);setCategories(v=>v.includes(key)?v.filter(x=>x!==key):[...v,key])};
 const clearGeometry=()=>{setPoints([])};
 const create=async()=>{if(areas.length>=3)return Alert.alert(t("alertAreas.maximumReached"),t("alertAreas.maximumReachedBody"));if(!name.trim())return Alert.alert(t("alertAreas.nameRequired"));if(mode==="POLYGON"&&points.length<3)return Alert.alert(t("alertAreas.morePointsTitle"),t("alertAreas.morePointsBody"));try{setBusy(true);const body:any={name:name.trim(),areaType:mode,allCategories,categoryKeys:categories,pushEnabled:true};if(mode==="CIRCLE")Object.assign(body,{latitude:center.latitude,longitude:center.longitude,radiusM:radius});else body.boundaryPoints=points;const r=await fetch(`${API_BASE_URL}/alert-areas`,{method:"POST",headers:await headers(),body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error);setName("");setPoints([]);await load();}catch(e:any){Alert.alert(t("alertAreas.error"),friendly(e,t("alertAreas.saveFailed")));}finally{setBusy(false)}};
 const patch=async(id:string,p:any)=>{await fetch(`${API_BASE_URL}/alert-areas/${id}`,{method:"PATCH",headers:await headers(),body:JSON.stringify(p)});await load()};
 const remove=async(id:string)=>{await fetch(`${API_BASE_URL}/alert-areas/${id}`,{method:"DELETE",headers:await headers()});await load()};
 const areaMeta=(item:Area)=>item.area_type==="POLYGON"?t("alertAreas.polygonType",{count:item.boundary_points?.length||0}):t("alertAreas.circleType",{radius:(item.radius_m||0)>=1000?`${(item.radius_m||0)/1000} km`:`${item.radius_m||0} m`});
 return <><Stack.Screen options={{headerShown:false}}/><View style={s.safe}><PremiumHeader title={t("alertAreas.title")} onBack={()=>router.back()}/>
 <MapView ref={mapRef} provider={Platform.OS==="android"?PROVIDER_GOOGLE:undefined} style={s.map} initialRegion={region} onPress={e=>mapPress(e.nativeEvent.coordinate)}>
  {mode==="CIRCLE"?<><Marker coordinate={center} draggable onDragEnd={e=>setCenter(e.nativeEvent.coordinate)}/><Circle center={center} radius={radius} strokeColor="#2563EB" fillColor="rgba(37,99,235,.15)"/></>:<>{points.map((p,i)=><Marker key={i} coordinate={p} pinColor="#F59E0B"/>)}{points.length>=3&&<Polygon coordinates={points} strokeColor="#2563EB" fillColor="rgba(37,99,235,.18)" strokeWidth={3}/>}</>}
 </MapView>
 <View style={s.searchBox}><View style={s.searchRow}><TextInput style={s.searchInput} value={query} onChangeText={setQuery} onSubmitEditing={()=>void search()} returnKeyType="search" placeholder={t("alertAreas.searchPlaceholder")}/><Pressable style={s.searchButton} onPress={()=>void search()}>{searching?<ActivityIndicator color="#fff"/>:<Text style={s.searchButtonText}>{t("alertAreas.search")}</Text>}</Pressable></View>{results.length>0&&<View style={s.results}>{results.map(x=><Pressable key={x.id||x.label} style={s.result} onPress={()=>chooseResult(x)}><Text numberOfLines={2}>{x.label}</Text></Pressable>)}</View>}</View>
 <View style={s.panel}><View style={s.modeRow}>{(["CIRCLE","POLYGON"] as AreaMode[]).map(x=><Pressable key={x} onPress={()=>{setMode(x);setPoints([])}} style={[s.mode,mode===x&&s.modeOn]}><Text style={[s.modeText,mode===x&&s.modeTextOn]}>{x==="CIRCLE"?t("alertAreas.place"):t("alertAreas.area")}</Text></Pressable>)}</View><Text style={s.help}>{mode==="CIRCLE"?t("alertAreas.tapPlace"):t("alertAreas.tapPolygon")}</Text>
 <TextInput value={name} onChangeText={setName} placeholder={t("alertAreas.namePlaceholder")} style={s.input}/>
 {mode==="CIRCLE"?<View style={s.row}>{RADII.map(r=><Pressable key={r} onPress={()=>setRadius(r)} style={[s.chip,radius===r&&s.chipOn]}><Text style={[s.chipText,radius===r&&s.chipTextOn]}>{r>=1000?`${r/1000} km`:`${r} m`}</Text></Pressable>)}</View>:<View style={s.geometryActions}><Text style={s.count}>{t("alertAreas.pointCount",{count:points.length})}</Text><Pressable onPress={()=>setPoints(v=>v.slice(0,-1))}><Text style={s.link}>{t("alertAreas.undo")}</Text></Pressable><Pressable onPress={clearGeometry}><Text style={s.delete}>{t("alertAreas.clear")}</Text></Pressable></View>}
 <Pressable onPress={()=>{setAllCategories(true);setCategories([])}} style={[s.all,allCategories&&s.chipOn]}><Text style={[s.chipText,allCategories&&s.chipTextOn]}>{t("alertAreas.allCategories")}</Text></Pressable><View style={s.row}>{CATEGORIES.map(k=><Pressable key={k} onPress={()=>toggle(k)} style={[s.chip,categories.includes(k)&&s.chipOn]}><Text style={[s.chipText,categories.includes(k)&&s.chipTextOn]}>{LABELS[k][language]}</Text></Pressable>)}</View>
 <View style={s.actions}><Pressable style={s.secondary} onPress={()=>void locate()}><Text style={s.secondaryText}>{t("alertAreas.myLocation")}</Text></Pressable><Pressable disabled={busy} style={[s.primary,busy&&s.disabled]} onPress={()=>void create()}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>{t("alertAreas.saveArea")}</Text>}</Pressable></View><Text style={s.count}>{areas.length} / 3</Text>
 <FlatList data={areas} keyExtractor={x=>x.id} horizontal renderItem={({item})=><View style={s.card}><Text style={s.cardTitle}>{item.name}</Text><Text style={s.cardMeta}>{areaMeta(item)} · {item.all_categories?t("alertAreas.allCategories"):t("alertAreas.categoryCount",{count:item.category_keys.length})}</Text><View style={s.miniActions}><Pressable onPress={()=>void patch(item.id,{active:!item.active})}><Text style={s.link}>{item.active?t("alertAreas.pause"):t("alertAreas.activate")}</Text></Pressable><Pressable onPress={()=>void remove(item.id)}><Text style={s.delete}>{t("alertAreas.delete")}</Text></Pressable></View></View>}/></View></View></>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.colors.bg},map:{flex:1},searchBox:{position:"absolute",top:74,left:12,right:12,zIndex:50,backgroundColor:"rgba(255,255,255,.98)",borderRadius:14,padding:8,borderWidth:1,borderColor:theme.colors.border},searchRow:{flexDirection:"row",gap:8},searchInput:{flex:1,minHeight:42,borderRadius:10,borderWidth:1,borderColor:theme.colors.border,paddingHorizontal:12},searchButton:{minWidth:62,minHeight:42,borderRadius:10,backgroundColor:theme.colors.primary,alignItems:"center",justifyContent:"center",paddingHorizontal:10},searchButtonText:{color:"#fff",fontWeight:"900"},results:{marginTop:6},result:{padding:9,borderTopWidth:1,borderTopColor:theme.colors.border},panel:{position:"absolute",left:12,right:12,bottom:18,backgroundColor:"rgba(255,255,255,.97)",borderRadius:18,padding:12,borderWidth:1,borderColor:theme.colors.border,maxHeight:"62%"},modeRow:{flexDirection:"row",gap:8},mode:{flex:1,minHeight:38,borderRadius:11,borderWidth:1,borderColor:theme.colors.border,alignItems:"center",justifyContent:"center"},modeOn:{backgroundColor:theme.colors.primary},modeText:{fontWeight:"900",color:theme.colors.muted},modeTextOn:{color:"#fff"},help:{marginTop:7,color:theme.colors.muted,fontWeight:"700",fontSize:12},input:{borderWidth:1,borderColor:theme.colors.border,borderRadius:12,padding:11,color:theme.colors.text,marginTop:8},row:{flexDirection:"row",flexWrap:"wrap",gap:6,marginTop:8},chip:{paddingHorizontal:9,paddingVertical:6,borderRadius:999,backgroundColor:"#F1F5F9"},chipOn:{backgroundColor:theme.colors.primary},chipText:{fontSize:11,fontWeight:"800",color:"#475569"},chipTextOn:{color:"#fff"},all:{alignSelf:"flex-start",marginTop:8,paddingHorizontal:10,paddingVertical:7,borderRadius:999,backgroundColor:"#F1F5F9"},geometryActions:{flexDirection:"row",alignItems:"center",gap:18,marginTop:9},actions:{flexDirection:"row",gap:8,marginTop:10},secondary:{flex:1,minHeight:42,borderRadius:12,borderWidth:1,borderColor:theme.colors.border,alignItems:"center",justifyContent:"center"},secondaryText:{fontWeight:"900",color:theme.colors.text},primary:{flex:1,minHeight:42,borderRadius:12,backgroundColor:theme.colors.primary,alignItems:"center",justifyContent:"center"},primaryText:{fontWeight:"900",color:"#fff"},disabled:{opacity:.45},count:{marginTop:8,color:theme.colors.muted,fontWeight:"900"},card:{width:210,marginTop:8,marginRight:8,padding:10,borderRadius:12,borderWidth:1,borderColor:theme.colors.border,backgroundColor:"#F8FAFC"},cardTitle:{fontWeight:"900",color:theme.colors.text},cardMeta:{marginTop:4,fontSize:11,fontWeight:"700",color:theme.colors.muted},miniActions:{flexDirection:"row",justifyContent:"space-between",marginTop:8},link:{color:theme.colors.primary,fontWeight:"900"},delete:{color:theme.colors.danger,fontWeight:"900"}});
