import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Alert, FlatList, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import MapView, { Circle, Marker, PROVIDER_GOOGLE, Region } from "react-native-maps";
import * as Location from "expo-location";
import { Stack, useRouter } from "expo-router";
import { PremiumHeader } from "../src/ui/PremiumHeader";
import { theme } from "../src/ui/theme";
import { useI18n } from "../src/i18n/I18nProvider";
import { supabase } from "../src/lib/supabase";
import { API_BASE_URL } from "../src/lib/config";

type Area = { id:string; name:string; latitude:number; longitude:number; radius_m:number; category_keys:string[]; all_categories:boolean; push_enabled:boolean; active:boolean };
const RADII=[250,500,1000,3000,5000,10000];
const CATEGORIES=["PETS","JEWELRY","ELECTRONICS","KEYS","BAGS","CLOTHING","SPORTS","TRANSPORT"];
const LABELS:Record<string,{no:string;en:string}>={PETS:{no:"Husdyr",en:"Pets"},JEWELRY:{no:"Smykker",en:"Jewelry"},ELECTRONICS:{no:"Elektronikk",en:"Electronics"},KEYS:{no:"Nøkler",en:"Keys"},BAGS:{no:"Vesker",en:"Bags"},CLOTHING:{no:"Klær",en:"Clothing"},SPORTS:{no:"Sport",en:"Sports"},TRANSPORT:{no:"Transport",en:"Transport"}};

export default function AlertAreasScreen(){
 const router=useRouter(); const {language,t}=useI18n(); const mapRef=useRef<MapView>(null);
 const [areas,setAreas]=useState<Area[]>([]); const [name,setName]=useState(""); const [point,setPoint]=useState({latitude:59.9139,longitude:10.7522}); const [radius,setRadius]=useState(1000); const [allCategories,setAllCategories]=useState(true); const [categories,setCategories]=useState<string[]>([]); const [busy,setBusy]=useState(false);
 const region=useMemo<Region>(()=>({...point,latitudeDelta:.08,longitudeDelta:.08}),[]);
 const headers=useCallback(async()=>{const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error("LOGIN_REQUIRED");return {"Content-Type":"application/json",Authorization:`Bearer ${token}`};},[language]);
 const load=useCallback(async()=>{try{const r=await fetch(`${API_BASE_URL}/alert-areas`,{headers:await headers()});const j=await r.json();if(!r.ok)throw new Error(j.error);setAreas(j.areas||[]);}catch{Alert.alert(t("alertAreas.error"),t("alertAreas.loadFailed"))}},[headers]);
 useEffect(()=>{load()},[load]);
 const locate=async()=>{const p=await Location.requestForegroundPermissionsAsync();if(p.status!=="granted")return;const pos=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});const next={latitude:pos.coords.latitude,longitude:pos.coords.longitude};setPoint(next);mapRef.current?.animateToRegion({...next,latitudeDelta:.03,longitudeDelta:.03},250)};
 const toggle=(key:string)=>{setAllCategories(false);setCategories(v=>v.includes(key)?v.filter(x=>x!==key):[...v,key])};
 const create=async()=>{if(areas.length>=3)return Alert.alert(t("alertAreas.maximumReached"),t("alertAreas.maximumReachedBody"));if(!name.trim())return Alert.alert(t("alertAreas.nameRequired"));try{setBusy(true);const r=await fetch(`${API_BASE_URL}/alert-areas`,{method:"POST",headers:await headers(),body:JSON.stringify({name:name.trim(),latitude:point.latitude,longitude:point.longitude,radiusM:radius,allCategories,categoryKeys:categories,pushEnabled:true})});const j=await r.json();if(!r.ok)throw new Error(j.error);setName("");await load();}catch{Alert.alert(t("alertAreas.error"),t("alertAreas.saveFailed"))}finally{setBusy(false)}};
 const patch=async(id:string,p:any)=>{await fetch(`${API_BASE_URL}/alert-areas/${id}`,{method:"PATCH",headers:await headers(),body:JSON.stringify(p)});await load()};
 const remove=async(id:string)=>{await fetch(`${API_BASE_URL}/alert-areas/${id}`,{method:"DELETE",headers:await headers()});await load()};
 return <><Stack.Screen options={{headerShown:false}}/><View style={s.safe}><PremiumHeader title={t("alertAreas.title")} onBack={()=>router.back()}/><MapView ref={mapRef} provider={Platform.OS==="android"?PROVIDER_GOOGLE:undefined} style={s.map} initialRegion={region} onPress={e=>setPoint(e.nativeEvent.coordinate)}><Marker coordinate={point} draggable onDragEnd={e=>setPoint(e.nativeEvent.coordinate)}/><Circle center={point} radius={radius} strokeColor="#2563EB" fillColor="rgba(37,99,235,.15)"/></MapView><View style={s.panel}><TextInput value={name} onChangeText={setName} placeholder={t("alertAreas.namePlaceholder")} style={s.input}/><View style={s.row}>{RADII.map(r=><Pressable key={r} onPress={()=>setRadius(r)} style={[s.chip,radius===r&&s.chipOn]}><Text style={[s.chipText,radius===r&&s.chipTextOn]}>{r>=1000?`${r/1000} km`:`${r} m`}</Text></Pressable>)}</View><Pressable onPress={()=>{setAllCategories(true);setCategories([])}} style={[s.all,allCategories&&s.chipOn]}><Text style={[s.chipText,allCategories&&s.chipTextOn]}>{t("alertAreas.allCategories")}</Text></Pressable><View style={s.row}>{CATEGORIES.map(k=><Pressable key={k} onPress={()=>toggle(k)} style={[s.chip,categories.includes(k)&&s.chipOn]}><Text style={[s.chipText,categories.includes(k)&&s.chipTextOn]}>{LABELS[k][language]}</Text></Pressable>)}</View><View style={s.actions}><Pressable style={s.secondary} onPress={locate}><Text style={s.secondaryText}>{t("alertAreas.myLocation")}</Text></Pressable><Pressable disabled={busy} style={s.primary} onPress={create}><Text style={s.primaryText}>{t("alertAreas.saveArea")}</Text></Pressable></View><Text style={s.count}>{areas.length} / 3</Text><FlatList data={areas} keyExtractor={x=>x.id} horizontal renderItem={({item})=><View style={s.card}><Text style={s.cardTitle}>{item.name}</Text><Text style={s.cardMeta}>{item.radius_m>=1000?`${item.radius_m/1000} km`:`${item.radius_m} m`} · {item.all_categories?(t("alertAreas.allCategories")):t("alertAreas.categoryCount",{count:item.category_keys.length})}</Text><View style={s.miniActions}><Pressable onPress={()=>patch(item.id,{active:!item.active})}><Text style={s.link}>{item.active?(t("alertAreas.pause")):(t("alertAreas.activate"))}</Text></Pressable><Pressable onPress={()=>remove(item.id)}><Text style={s.delete}>{t("alertAreas.delete")}</Text></Pressable></View></View>}/></View></View></>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.colors.bg},map:{flex:1},panel:{position:"absolute",left:12,right:12,bottom:18,backgroundColor:"rgba(255,255,255,.97)",borderRadius:18,padding:12,borderWidth:1,borderColor:theme.colors.border,maxHeight:"58%"},input:{borderWidth:1,borderColor:theme.colors.border,borderRadius:12,padding:11,color:theme.colors.text},row:{flexDirection:"row",flexWrap:"wrap",gap:6,marginTop:8},chip:{paddingHorizontal:9,paddingVertical:6,borderRadius:999,backgroundColor:"#F1F5F9"},chipOn:{backgroundColor:theme.colors.primary},chipText:{fontSize:11,fontWeight:"800",color:"#475569"},chipTextOn:{color:"#fff"},all:{alignSelf:"flex-start",marginTop:8,paddingHorizontal:10,paddingVertical:7,borderRadius:999,backgroundColor:"#F1F5F9"},actions:{flexDirection:"row",gap:8,marginTop:10},secondary:{flex:1,minHeight:42,borderRadius:12,borderWidth:1,borderColor:theme.colors.border,alignItems:"center",justifyContent:"center"},secondaryText:{fontWeight:"900",color:theme.colors.text},primary:{flex:1,minHeight:42,borderRadius:12,backgroundColor:theme.colors.primary,alignItems:"center",justifyContent:"center"},primaryText:{fontWeight:"900",color:"#fff"},count:{marginTop:8,color:theme.colors.muted,fontWeight:"900"},card:{width:190,marginTop:8,marginRight:8,padding:10,borderRadius:12,borderWidth:1,borderColor:theme.colors.border,backgroundColor:"#F8FAFC"},cardTitle:{fontWeight:"900",color:theme.colors.text},cardMeta:{marginTop:4,fontSize:11,fontWeight:"700",color:theme.colors.muted},miniActions:{flexDirection:"row",justifyContent:"space-between",marginTop:8},link:{color:theme.colors.primary,fontWeight:"900"},delete:{color:theme.colors.danger,fontWeight:"900"}});
