"use strict";
const REPORT_PRODUCT_CODES = Object.freeze({
  REPORT_REACTIVATION: "REPORT_REACTIVATION",
  GEO_ALERT_TIER_1: "GEO_ALERT_TIER_1",
  GEO_ALERT_TIER_2: "GEO_ALERT_TIER_2",
  GEO_ALERT_TIER_3: "GEO_ALERT_TIER_3",
  GEO_ALERT_TIER_4: "GEO_ALERT_TIER_4",
  GEO_ALERT_TIER_5: "GEO_ALERT_TIER_5",
  LONG_TERM_WATCH_ANNUAL: "LONG_TERM_WATCH_ANNUAL",
});
module.exports = { REPORT_PRODUCT_CODES };
